import { Aposta } from '@/types/aposta';

// ============================================================
// Mock data — futebol (Brasileirão) + basquete (NBA)
// ============================================================
export const MOCK_APOSTAS: Aposta[] = [
  // --- GREENS ---
  {
    id: 'mock-001',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 30 * 86400000).toISOString(),
    times_apostados: 'Flamengo vs Palmeiras',
    detalhe_aposta: 'Flamengo Vence (Tempo Normal)',
    odd: 2.1,
    stake: 100,
    status: 'Green',
  },
  {
    id: 'mock-002',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 28 * 86400000).toISOString(),
    times_apostados: 'Los Angeles Lakers vs Golden State Warriors',
    detalhe_aposta: 'Lakers Vence + Over 220.5 pontos',
    odd: 1.85,
    stake: 150,
    status: 'Green',
  },
  {
    id: 'mock-003',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 25 * 86400000).toISOString(),
    times_apostados: 'Corinthians vs São Paulo',
    detalhe_aposta: 'Ambas Marcam — SIM',
    odd: 1.75,
    stake: 80,
    status: 'Green',
  },
  {
    id: 'mock-004',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 22 * 86400000).toISOString(),
    times_apostados: 'Boston Celtics vs Miami Heat',
    detalhe_aposta: 'Celtics -5.5 (Handicap)',
    odd: 1.9,
    stake: 200,
    status: 'Green',
  },
  {
    id: 'mock-005',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 20 * 86400000).toISOString(),
    times_apostados: 'Atlético-MG vs Cruzeiro',
    detalhe_aposta: 'Atlético-MG Vence + Over 2.5 Gols',
    odd: 2.4,
    stake: 60,
    status: 'Green',
  },
  {
    id: 'mock-006',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 18 * 86400000).toISOString(),
    times_apostados: 'Denver Nuggets vs Phoenix Suns',
    detalhe_aposta: 'Nikola Jokić Over 25.5 Pontos',
    odd: 1.95,
    stake: 100,
    status: 'Green',
  },
  {
    id: 'mock-007',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 15 * 86400000).toISOString(),
    times_apostados: 'Botafogo vs Vasco',
    detalhe_aposta: 'Botafogo Vence',
    odd: 1.7,
    stake: 120,
    status: 'Green',
  },
  // --- REDS ---
  {
    id: 'mock-008',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 24 * 86400000).toISOString(),
    times_apostados: 'Internacional vs Grêmio',
    detalhe_aposta: 'Internacional Vence (Gre-Nal)',
    odd: 2.3,
    stake: 100,
    status: 'Red',
  },
  {
    id: 'mock-009',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 21 * 86400000).toISOString(),
    times_apostados: 'Chicago Bulls vs Milwaukee Bucks',
    detalhe_aposta: 'Bulls Vence (Antepassado)',
    odd: 3.1,
    stake: 50,
    status: 'Red',
  },
  {
    id: 'mock-010',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 17 * 86400000).toISOString(),
    times_apostados: 'Santos vs Fortaleza',
    detalhe_aposta: 'Santos Vence em casa',
    odd: 2.0,
    stake: 80,
    status: 'Red',
  },
  {
    id: 'mock-011',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 14 * 86400000).toISOString(),
    times_apostados: 'Oklahoma City Thunder vs Dallas Mavericks',
    detalhe_aposta: 'Thunder -3.5 (Handicap)',
    odd: 1.85,
    stake: 130,
    status: 'Red',
  },
  {
    id: 'mock-012',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 12 * 86400000).toISOString(),
    times_apostados: 'Fluminense vs Bahia',
    detalhe_aposta: 'Fluminense Vence + Under 3.5 gols',
    odd: 2.15,
    stake: 90,
    status: 'Red',
  },
  // --- VOID ---
  {
    id: 'mock-013',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 10 * 86400000).toISOString(),
    times_apostados: 'Bragantino vs Athletico-PR',
    detalhe_aposta: 'Bragantino Vence — Jogo adiado',
    odd: 1.8,
    stake: 70,
    status: 'Void',
  },
  // --- ABERTAS ---
  {
    id: 'mock-014',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 5 * 86400000).toISOString(),
    times_apostados: 'Flamengo vs Athletico-PR',
    detalhe_aposta: 'Flamengo Vence + Gabigol Marca',
    odd: 2.6,
    stake: 100,
    status: 'Aberta',
  },
  {
    id: 'mock-015',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 3 * 86400000).toISOString(),
    times_apostados: 'New York Knicks vs Indiana Pacers',
    detalhe_aposta: 'Over 224.5 Pontos',
    odd: 1.92,
    stake: 110,
    status: 'Aberta',
  },
  {
    id: 'mock-016',
    user_id: 'mock-user',
    data_criacao: new Date(Date.now() - 1 * 86400000).toISOString(),
    times_apostados: 'Palmeiras vs Flamengo',
    detalhe_aposta: 'Empate ou Palmeiras Vence (Chance Dupla)',
    odd: 1.55,
    stake: 200,
    status: 'Aberta',
  },
];

export const VOICE_SUGGESTIONS = [
  'Flamengo vs Palmeiras, Flamengo vence com handicap',
  'Lakers vs Celtics, Lakers vence e over 210 pontos',
  'Corinthians vs São Paulo, ambas as equipes marcam',
  'Golden State Warriors vs Miami Heat, Warriors vencem',
  'Atlético-MG vs Cruzeiro, gol no primeiro tempo',
];
